# Generated by Django 6.0.6 on 2026-06-23 12:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_poste_obs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='poste',
            name='nome',
        ),
    ]
